services:
  - type: web
    name: educate4dignity-web-service
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true

staticSites:
  - name: educate4dignity-static
    buildCommand: npm ci && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html
